<?php

namespace PayloadEntityGenerator\Handler;

use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Property;
use Nette\PhpGenerator\PhpNamespace;

class EntityGenerator
{
    public function generate(string $className, array $schema): PhpFile
    {
        $namespace = new PhpNamespace('Model');
        $class = $namespace->addClass($className);
        $class->addComment('Autogenerated Model');

        foreach ($schema as $propertyName => $item) {
            $property = new Property($propertyName);
            $property->setPublic();
            $property->setNullable(true);
            $property->setType($item['type']);

            $class->addMember($property);
            // todo recursive parser !
        }

        $phpFile = new PhpFile();
        $phpFile->addNamespace($namespace);

        return $phpFile;
    }
}
