<?php

namespace App\Tests\Feature;

use EntityGenerator\Bridge\Symfony\ParameterBag;
use EntityGenerator\Type\ConfigurationType;
use EntityGenerator\Handler\GenerationProcess;
use EntityGenerator\Tests\KernelTestCase;

/**
 * @author Mounir Mouih <mounir.mouih@gmail.com>
 */
class EntityGenerationTest extends KernelTestCase
{
    public function testGenerate(): void
    {
        $generationProcess = $this->container()->get(GenerationProcess::class);
        $files = $generationProcess->handle(new ConfigurationType(
            className: 'User',
            payload: __DIR__ . '/../data/user.json',
            file: true,
            format: 'json',
        ));

        $this->assertCount(6, $files);
        // clean up created files
        foreach ($files as $file) {
            unlink($file);
        }
    }

    public function testGenerateFromInput(): void
    {
        $generationProcess = $this->container()->get(GenerationProcess::class);
        $files = $generationProcess->handle(new ConfigurationType(
            className : 'User',
            payload : json_encode([
                "id" => 2,
                "name" => "john doe",
                "account" => ['account_id' => 1, 'label' => null],
                'details' => [
                    ['uid' => 'ccsf', 'sample' => 'hello'],
                    ['uid' => 'cfsx', 'sample' => null],
                ]
            ]),
            file : false,
            format : 'json',
        ));

        $this->assertCount(3, $files);
        $detailFile = $this->container()->get(ParameterBag::class)->get('output.dir') . DIRECTORY_SEPARATOR . 'Detail.php';
        $this->assertFileExists($detailFile);
        $expected = <<<EOF
<?php

namespace Entity\Generated;

/**
 * Autogenerated Entity
 */
class Detail
{
    /** @var string */
    public string \$uid;

    /** @var string|null */
    public ?string \$sample;
}

EOF;
        $this->assertEquals($expected, file_get_contents($detailFile));

        // Test account file for nullable types
        $accountFile = $this->container()->get(ParameterBag::class)->get('output.dir') . DIRECTORY_SEPARATOR . 'Account.php';
        $this->assertFileExists($accountFile);
        $expected = <<<EOF
<?php

namespace Entity\Generated;

/**
 * Autogenerated Entity
 */
class Account
{
    /** @var int */
    public int \$accountId;

    /** @var null */
    public mixed \$label;
}

EOF;
        $this->assertEquals($expected, file_get_contents($accountFile));
        // clean up created files
        foreach ($files as $file) {
            unlink($file);
        }
    }

    public function testFileNotExist(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $generationProcess = $this->container()->get(GenerationProcess::class);
        $generationProcess->handle(new ConfigurationType(
            className : 'User',
            payload: __DIR__ . '/../data/user1.cson',
            file: true,
            format: 'json',
        ));
    }
}
