services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EntityGenerator\:
      autowire: true
      resource: '../src/'
      exclude:
          - '../src/Type/'
          - '../src/Bridge/Nette/Wrapper/'

    Symfony\Component\Serializer\Normalizer\DenormalizerInterface:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface:
      class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~
    Symfony\Component\String\Inflector\StringProcessor: ~
    Symfony\Component\String\Inflector\EnglishInflector: ~
    Symfony\Component\Serializer\Encoder\JsonDecode: ~
    Symfony\Component\Serializer\Encoder\XmlEncoder: ~
    Symfony\Component\Serializer\Encoder\YamlEncoder: ~
    Nette\PhpGenerator\ClassType: ~
    Nette\PhpGenerator\PsrPrinter: ~
    Nette\Utils\FileSystem: ~