services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
      Symfony\Component\Console\Command\Command:
        tags: ['command']

    EntityGenerator\:
      autowire: true
      resource: '../src/'
      exclude:
          - '../src/Type/'
          - '../src/Bridge/Nette/Wrapper/'
  
    Symfony\Component\Serializer\Normalizer\DenormalizerInterface:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    
    Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface:
      class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag

    EntityGenerator\Bridge\Symfony\ParameterBagInterface:
      class: EntityGenerator\Bridge\Symfony\ParameterBag

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~
    Symfony\Component\String\Inflector\StringProcessor: ~
    Symfony\Component\String\Inflector\EnglishInflector: ~
    Symfony\Component\Serializer\Encoder\JsonDecode: ~
    Symfony\Component\Serializer\Encoder\XmlEncoder: ~
    Symfony\Component\Serializer\Encoder\YamlEncoder: ~
    Symfony\Component\DependencyInjection\Loader\YamlFileLoader: ~
    Symfony\Component\DependencyInjection\ContainerBuilder: ~
    Nette\PhpGenerator\ClassType: ~
    Nette\PhpGenerator\PsrPrinter: ~
    Nette\Utils\FileSystem: ~

    EntityGenerator\BaseApplication:
      public: true
      arguments:
        - !tagged_iterator command