parameters:
  printer.params: 
    print_dir: 'var/generated'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
      Symfony\Component\Console\Command\Command:
        tags: ['command']

    EntityGenerator\:
      autowire: true
      resource: '../src/'

    EntityGenerator\Handler\EntityPrinter:
      arguments:
          $parameters: '%printer.params%'

    Symfony\Component\Serializer\Normalizer\DenormalizerInterface:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    Symfony\Component\Serializer\Encoder\JsonDecode: ~
    Nette\PhpGenerator\ClassType: ~
    Nette\PhpGenerator\PsrPrinter: ~
    Nette\Utils\FileSystem: ~

    EntityGenerator\BaseApplication:
      public: true
      arguments:
        - !tagged_iterator command