services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
      Symfony\Component\Console\Command\Command:
        tags: ['command']

    PayloadEntityGenerator\:
      autowire: true
      resource: '../src/'

    Symfony\Component\Serializer\Normalizer\DenormalizerInterface:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    Symfony\Component\Serializer\Encoder\JsonDecode: ~

    PayloadEntityGenerator\BaseApplication:
      public: true
      arguments:
        - !tagged_iterator command