parameters:
  printer.params: 
    print_dir: 'var/generated'
  entity.generator.params: 
    namespace: 'Entity\Generated'
    property.phpdoc: true
    property.type: true # false before php7.4

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
      Symfony\Component\Console\Command\Command:
        tags: ['command']

    EntityGenerator\:
      autowire: true
      resource: '../src/'

    EntityGenerator\Handler\Printer:
      arguments:
          $parameters: '%printer.params%'
    
    EntityGenerator\Handler\EntityGenerator:
      arguments:
          $parameters: '%entity.generator.params%'
    EntityGenerator\Handler\Property\AtomicType:
      arguments:
          $parameters: '%entity.generator.params%'
    EntityGenerator\Handler\Property\CollectionType:
      arguments:
          $parameters: '%entity.generator.params%'

    Symfony\Component\Serializer\Normalizer\DenormalizerInterface:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~
    Symfony\Component\String\Inflector\StringProcessor: ~
    Symfony\Component\String\Inflector\EnglishInflector: ~
    Symfony\Component\Serializer\Encoder\JsonDecode: ~
    Nette\PhpGenerator\ClassType: ~
    Nette\PhpGenerator\PsrPrinter: ~
    Nette\Utils\FileSystem: ~

    EntityGenerator\BaseApplication:
      public: true
      arguments:
        - !tagged_iterator command