name: Makefile CI 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check coding styles
      run: make cs

    - name: Static analysis
      run: make analyse
