name: Makefile CI 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.2
          coverage: none


    - name: Validate composer 
      run: make validate

    - name: Build & install dependencies
      run: make build
    
    - name: Check coding styles
      run: make cs

    - name: Static analysis
      run: make review
    
    - name: Test suite
      run: make test
