name: Makefile CI 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        php-version: '8.2'


    - name: Build & install dependencies
      run: make build
    
    - name: Check coding styles
      run: make cs

    - name: Static analysis
      run: make analyze
    
    - name: Test suite
      run: make test
